//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCardApp.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int idAnswer { get; set; }
        public Nullable<int> idWorkingCard { get; set; }
        public Nullable<int> idPoint { get; set; }
        public Nullable<int> idUser { get; set; }
        public string Answer { get; set; }
    
        public virtual Points Points { get; set; }
        public virtual Users Users { get; set; }
        public virtual WorkingCards WorkingCards { get; set; }
    }
}
