//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCardApp.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingCards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkingCards()
        {
            this.Answers = new HashSet<Answers>();
        }
    
        public int idWorkingCard { get; set; }
        public Nullable<int> idTemplate { get; set; }
        public string SerialNumber { get; set; }
        public string FactoryNumber { get; set; }
        public Nullable<System.DateTime> DateOfAcceptance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answers> Answers { get; set; }
        public virtual Templates Templates { get; set; }
    }
}
